//
//  OnBoardingRouter.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol OnBoardingRoutingLogic {
    func routeToDashboard(segue: UIStoryboardSegue?)
}

protocol OnBoardingDataPassing {
    var dataStore: OnBoardingDataStore? { get }
}

class OnBoardingRouter: NSObject, OnBoardingRoutingLogic, OnBoardingDataPassing {
    weak var viewController: OnBoardingViewController?
    var dataStore: OnBoardingDataStore?
  
  // MARK: Routing
    func routeToDashboard(segue: UIStoryboardSegue?) {
        let storyBoard : UIStoryboard = UIStoryboard(name: "Main", bundle:nil)
        let dashboardVC = storyBoard.instantiateViewController(withIdentifier: "TabBarController")
//        self.definesPresentationContext = true
        dashboardVC.modalPresentationStyle = .fullScreen
        navigateToSomewhere(source: viewController!, destination: dashboardVC as! UITabBarController)
        
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  }

  // MARK: Navigation
    
    func navigateToSomewhere(source: OnBoardingViewController, destination: UITabBarController) {
        source.show(destination, sender: nil)
//        source.present(destination, animated:true, completion:nil)

    }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: OnBoardingDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
