//
//  OnBoardingInteractor.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnBoardingBusinessLogic {
    func getOnboardingData(request: OnBoardingModels.LoadOnboarding.Request)
}

protocol OnBoardingDataStore {
  //var name: String { get set }
}

class OnBoardingInteractor: OnBoardingBusinessLogic, OnBoardingDataStore {
    var presenter: OnBoardingPresentationLogic?
    var worker: OnBoardingWorker?
  //var name: String = ""
    var onBoarding = [Onboarding]()
  
  // MARK: Do something
  
    func getOnboardingData(request: OnBoardingModels.LoadOnboarding.Request) {
        worker = OnBoardingWorker()
        onBoarding = worker!.fetchOnBoard()
    
        let response = OnBoardingModels.LoadOnboarding.Response(OnboardingData: onBoarding)
        presenter?.presentOnboardingData(response: response)
    }
}
