//
//  OnBoardingViewController.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Kingfisher

protocol OnBoardingDisplayLogic: AnyObject {
    func presenter(displayOnboard response: OnBoardingModels.FetchOnBoarding.Response)
}

class OnBoardingViewController: UIViewController, OnBoardingDisplayLogic {
    
    var interactor: OnBoardingBusinessLogic?
    var router: (NSObjectProtocol & OnBoardingRoutingLogic & OnBoardingDataPassing)?

  // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
  // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = OnBoardingInteractor()
        let presenter = OnBoardingPresenter()
        let router = OnBoardingRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
  // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
            if scene == "RegisterSegue" {
                router?.perform(selector)
            }
        }
    }
  
  // MARK: View lifecycle
    
    override func viewDidAppear(_ animated: Bool) {
        self.navigationController?.interactivePopGestureRecognizer?.delegate = self
    }
    
    override func viewDidLoad() {
        self.navigationController!.setNavigationBarHidden(true, animated: false)
        super.viewDidLoad()
        setOnboarding()
    }
    
    override func loadView() {
        super.loadView()
        setupViewNib()
    }
  
  // MARK: Do something
    
    let userDefault = UserDefaults.standard
    weak var onboardingView: OnBoardingView!
    
    var onboardSlide: [Onboarding] = [Onboarding]() {
        didSet{
            self.onboardingView.collView.reloadData()
        }
    }
    
    var currentPage: Int! {
        didSet {
            let modifier = AnyModifier { request in
                var r = request
                r.setValue(ConstantAPI.Server.apiKey, forHTTPHeaderField: ConstantAPI.HttpHeaderField.apikey.rawValue)
                return r
            }
            let imgUrl = URL(string: ConstantAPI.Server.baseURL+"/images/onboarding/\(onboardSlide[currentPage].image!)")
            self.onboardingView.imgViewOnboard.kf.setImage(with: imgUrl, placeholder: nil, options: [.requestModifier(modifier)], completionHandler: nil)
            onboardingView.imgViewOnboard.setImage(onboardingView.imgViewOnboard.image, animated: true)
        }
    }
    
    func setOnboarding() {
        let request = OnBoardingModels.FetchOnBoarding.Request()
        interactor?.loadOnboard(request: request)
        SetupUI()
    }
    
    private func setupViewNib() {
        let screenRect = UIScreen.main.bounds
        let screenWidth = screenRect.size.width
        let screenHeight = screenRect.size.height
        
        let onboardingViews = OnBoardingView(frame: CGRect(x: 0, y: 0, width: screenWidth, height: screenHeight))
        self.view = onboardingViews
//        self.view.addview(dashboardViews)
        
        self.onboardingView = onboardingViews
        self.onboardingView.delegate = self
    }
    
    func SetupUI() {
        onboardingView.collView.delegate = self
        onboardingView.collView.dataSource = self
    }
    
    func presenter(displayOnboard response: OnBoardingModels.FetchOnBoarding.Response) {
        if let onboard = response.success.result {
            onboardSlide.append(contentsOf: onboard)
            currentPage = 0
        }
    }
}

// MARK: Button and Page Controll Action
extension OnBoardingViewController: OnboardingButtonDelegate {
    func didTapLoginButton() {
        userDefault.setValue(true, forKey: "isLogin")
        router?.routeToLogin(segue: nil)
    }
    
    func didTapSkipButton() {
        currentPage = onboardSlide.count - 1
        onboardingView.pageControl.currentPage = currentPage
        var frame: CGRect = self.onboardingView.collView.frame
        frame.origin.x = frame.size.width * CGFloat(currentPage ?? 0)
        frame.origin.y = 0
        self.onboardingView.collView.scrollRectToVisible(frame, animated: true)
    }
    
    func didTapRegisterButton() {
        userDefault.setValue(false, forKey: "isLogin")
        router?.routeToSignUp(segue: nil)
    }
    
    func didTapPageControl(sender: UIPageControl) {
        let page: Int? = sender.currentPage
        var frame: CGRect = self.onboardingView.collView.frame
        frame.origin.x = frame.size.width * CGFloat(page ?? 0)
        frame.origin.y = 0
        currentPage = page!
        self.onboardingView.collView.scrollRectToVisible(frame, animated: true)
    }
}

extension OnBoardingViewController: UIGestureRecognizerDelegate {
//    func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
//        if gestureRecognizer.isEqual(navigationController?.interactivePopGestureRecognizer) {
//            navigationController?.popViewController(animated: true)
//        }
//        return false
//    }
    // MARK: Without this code below, the interactive swipe popVC still works
    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        return true
    }
}


//MARK: - Collection View
extension OnBoardingViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return onboardSlide.count
    }
    

    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: OnboardingCollectionViewCell.identifier, for: indexPath) as! OnboardingCollectionViewCell
        let slideObj = onboardSlide[indexPath.row]
        cell.setupView(slideObj)
        return cell
    }
    
    //MARK: - FlowLayout
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        let screenWidth = collectionView.frame.size.width
        let screenHeight = collectionView.frame.size.height
        return CGSize(width: screenWidth, height: screenHeight)
    }
    
    func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        let width = scrollView.frame.width
        currentPage = Int(scrollView.contentOffset.x/width)
        
        onboardingView.pageControl.currentPage = currentPage
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return 0
    }
}
 
