//
//  OnBoardingWorker.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnBoardingWorkerProtocol: AnyObject {
    func getOnboarding(completionHandler: @escaping (Result<OnBoardingModels.FetchOnBoarding.Response, APIError>) -> Void)
}

class OnBoardingWorker: OnBoardingWorkerProtocol {
    
    // MARK: - Private Properties
    private var service: ClientAPIOnboardingProtocol
    
    // MARK: - Init
    init(_ service: ClientAPIOnboardingProtocol = ClientAPI()) {
        self.service = service
    }
    
    func getOnboarding(completionHandler: @escaping (Result<OnBoardingModels.FetchOnBoarding.Response, APIError>) -> Void) {
        service.getOnboarding(completionHandler: { result in
            switch result {
            case .success(let value):
                completionHandler(.success(value))
            case .failure(let error):
                completionHandler(.failure(APIError(status: error.status, message: error.message)))
            }
        })
    }
}
