//
//  OnBoardingInteractor.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnBoardingBusinessLogic {
    func loadOnboard(request: OnBoardingModels.FetchOnBoarding.Request)
}

protocol OnBoardingDataStore {
  //var name: String { get set }
}

class OnBoardingInteractor: OnBoardingBusinessLogic, OnBoardingDataStore {
    
    var presenter: OnBoardingPresentationLogic?
    var worker = OnBoardingWorker()
  //var name: String = ""
  
  // MARK: Do something
    func loadOnboard(request: OnBoardingModels.FetchOnBoarding.Request) {
        worker.getOnboarding(completionHandler: { result in
            switch result {
            case .success(let value):
                self.presenter?.interactor(displayOnboard: value)
            case .failure(let error):
                print(error.status, error.message!)
            }
        })
    }
}
