//
//  OnBoardingModels.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OnBoardingModels {
  // MARK: Use cases
    enum FetchOnBoarding {
        struct Request{}
        struct Response: Codable{
            var success: GenericSuccess.Success<[Onboarding]>
        }
    }
}
