//
//  NotificationWorker.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/29/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NotificationWorker {
    
    var notificationData = [Notification]()
    
    func fetchNotificationList() -> [Notification] {
    
        notificationData = [
            Notification(title: "Check In / Out", description: "Check Out - Out of Office", date: "29-Mar-2022"),
            Notification(title: "Check In / Out", description: "Check In - Out of Office", date: "29-Mar-2022"),
            Notification(title: "Check In / Out", description: "Check Out - Out of Office", date: "28-Mar-2022"),
            Notification(title: "Check In / Out", description: "Check In - Out of Office", date: "28-Mar-2022")
        ]
        return notificationData
    }
}
