//
//  NotificationInteractor.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/29/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotificationBusinessLogic {
    func loadDashboardListIn(request: NotificationModels.FetchNotification.Request)
}

protocol NotificationDataStore {
  //var name: String { get set }
}

class NotificationInteractor: NotificationBusinessLogic, NotificationDataStore {
    
    var presenter: NotificationPresentationLogic?
    var worker: NotificationWorker?
  //var name: String = ""
    
    var notificationList = [Notification]()
  
  // MARK: Do something
  
    func loadDashboardListIn(request: NotificationModels.FetchNotification.Request) {
        worker = NotificationWorker()
        if let worker = worker {
            notificationList = worker.fetchNotificationList()
        }
        if let presenter = presenter {
            let response = NotificationModels.FetchNotification.Response(notificationData: notificationList)
            presenter.presentNotificationList(response: response)
        }
    }
}
