//
//  NotificationModels.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/29/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NotificationModels {
  // MARK: Use cases
  
    enum FetchNotification {
        struct Request {}
        struct Response {
            var notificationData: [Notification]
            
        }
        struct ViewModel {
            var title: String?
            var description: String?
            var date: String?
        }
    }
}
