# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'phincon-attendance-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher', '~> 7.0'
  pod 'Alamofire', '~> 5.4'
  pod 'SkeletonView'
  # pod 'RxSwift', '~> 6.2'
  # pod 'RxCocoa', '~> 6.2'

  # Pods for phincon-attendance-app

  target 'phincon-attendance-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'phincon-attendance-appUITests' do
    # Pods for testing
  end

end
