//
//  HistoryPresenter.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/22/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryPresentationLogic {
    func presentHistory(response: HistoryModel.LoadHistory.Response)
    func interactor(LoadHistory response: HistoryModel.FetchHistory.Response)
}

class HistoryPresenter: HistoryPresentationLogic {
    weak var viewController: HistoryDisplayLogic?
    
    // MARK: Do something
    func interactor(LoadHistory response: HistoryModel.FetchHistory.Response) {
        viewController?.presenter(LoadHistory: response)
    }
    
    func presentHistory(response: HistoryModel.LoadHistory.Response) {
//        let viewModel = HistoryModel.LoadHistory.ViewModel()
        let response = HistoryModel.LoadHistory.Response(HistoryData: response.HistoryData)        
        viewController?.displayHistoryList(history: response)
    }
}
