//
//  HistoryRouter.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/22/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SafariServices

@objc protocol HistoryRoutingLogic {
    func routeToSafariLink(segue: UIStoryboardSegue?)
}

protocol HistoryDataPassing {
    var dataStore: HistoryDataStore? { get }
}

class HistoryRouter: NSObject, HistoryRoutingLogic, HistoryDataPassing {
    weak var viewController: HistoryViewController?
    var dataStore: HistoryDataStore?
  
  // MARK: Routing
    func routeToSafariLink(segue: UIStoryboardSegue?) {
        
        if let historyDatas = dataStore {
            let urls = historyDatas.desc.replacingOccurrences(of: " ", with: "+")
            guard let url = URL(string: "https://www.google.com/maps/search/\(urls)") else { return }
            
            let svc = SFSafariViewController(url: url)
            navigateToSafariLink(source: viewController!, destination: svc)
        }
        
//        let urls = dataStore!.desc.replacingOccurrences(of: " ", with: "+")
//        guard let url = URL(string: "https://www.google.com/maps/search/\(urls)") else { return }
//        UIApplication.shared.open(url)
    }

  // MARK: Navigation
    func navigateToSafariLink(source: HistoryViewController, destination: SFSafariViewController) {
        source.show(destination, sender: nil)
//        viewController?.present(svc, animated: true, completion: nil)
    }
}
