//
//  HistoryRouter.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/22/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SafariServices

@objc protocol HistoryRoutingLogic
{
  func routeToSafariLink(segue: UIStoryboardSegue?)
}

protocol HistoryDataPassing
{
  var dataStore: HistoryDataStore? { get }
}

class HistoryRouter: NSObject, HistoryRoutingLogic, HistoryDataPassing {
    weak var viewController: HistoryViewController?
    var dataStore: HistoryDataStore?
  
  // MARK: Routing
    
    func routeToSafariLink(segue: UIStoryboardSegue?) {
        let urls = dataStore!.desc.replacingOccurrences(of: " ", with: "+")
        guard let url = URL(string: "https://www.google.com/maps/search/\(urls)") else { return }
//        UIApplication.shared.open(url)
        
        let svc = SFSafariViewController(url: url)
        viewController?.present(svc, animated: true, completion: nil)

//        if let segue = segue {
//            let destinationVC = segue.destination as! HistoryViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSafariLink(source: dataStore!)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! UIApplication
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataSafariLink(source: dataStore!, destination: &destinationDS)
//            navigateToSafariLink(source: viewController!, destination: destinationVC)
//        }
    }
  //func routeToSafariLink(segue: UIStoryboardSegue?) {
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
//    func navigateToSafariLink(source: HistoryViewController, destination: UIApplication) {
//        source.show(destination, sender: nil)
//    }
  
  // MARK: Passing data
    
//    func passDataToSafariLink(source: HistoryDataStore) {
//    destination.name = source.name
//    }
}
