//
//  HistoryWorker.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/22/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HistoryWorker {
    
    let json = """
        [
            {
                "title": "PT. Phincon",
                "desc": "Office. 88 @Kasablanka Office Tower 18th Floor",
                "type": "Check In",
                "time": "9:00 AM",
                "image": "https://avatars.githubusercontent.com/u/60510709?v=4"
            }
        ]
    """
    
    var history = [History]()
    
    func fetchHistory() -> [History]{
        history = [
            History(title: "PT. Phincon", desc: "Office. 88 @Kasablanka Office Tower 18th Floor", type: "Check In", time: "9:00 AM", image: #imageLiteral(resourceName: "dashboard-list-1")),
            History(title: "PT. Phincon", desc: "Office. 88 @Kasablanka Office Tower 18th Floor", type: "Check Out", time: "18:00 AM", image: #imageLiteral(resourceName: "dashboard-list-1")),
            History(title: "TSO", desc: "The Telkom Hub, Jl. Gatot Subroto No.Kav. 52, Kota Jakarta Selatan", type: "Check In", time: "9:00 AM", image: #imageLiteral(resourceName: "dashboard-list-2")),
            History(title: "TSO", desc: "The Telkom Hub, Jl. Gatot Subroto No.Kav. 52, Kota Jakarta Selatan", type: "Check Out", time: "20:00 AM", image: #imageLiteral(resourceName: "dashboard-list-2")),
            History(title: "PT. Phincon", desc: "Office. 88 @Kasablanka Office Tower 18th Floor", type: "Check In", time: "9:00 AM", image: #imageLiteral(resourceName: "dashboard-list-1")),
            History(title: "PT. Phincon", desc: "Office. 88 @Kasablanka Office Tower 18th Floor", type: "Check Out", time: "18:00 AM", image: #imageLiteral(resourceName: "dashboard-list-1")),
            History(title: "Telkomsel Smart Office", desc: "Jl. Jend. Gatot Subroto Kav. 52. Jakarta Selatan", type: "Check In", time: "9:00 AM", image: #imageLiteral(resourceName: "dashboard-list-2"))

        ]
        return history
    }
    func fetchUserHistory() {
//        let decoder = JSONDecoder()
//        let jsonData = json.data(using: .utf8)
//        let historyData = try! decoder.decode(History.self, from: jsonData!)
//        return historyData
        
//        let encoder = JSONEncoder()
//        if let jsonData = try? encoder.encode(history) {
//            if let jsonString = String(data: jsonData, encoding: .utf8) {
//                print(jsonString)
//            }
//        }
    }
        
}
