//
//  HistoryPresenter.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/22/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryPresentationLogic {
    func interactor(LoadHistory response: HistoryModels.FetchHistory.Response)
}

class HistoryPresenter: HistoryPresentationLogic {
    weak var viewController: HistoryDisplayLogic?
    
    // MARK: Do something
    func interactor(LoadHistory response: HistoryModels.FetchHistory.Response) {
        viewController?.presenter(LoadHistory: response)
    }
}
