//
//  SplashScreenWorker.swift
//  phincon-attendance-app
//
//  Created by Ade on 4/25/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashScreenWorkerProtocol {
    func getSplashScreen(completionHandler: @escaping (Result<SplashScreenModels.Fetch.Response, APIError>) -> Void)
}

class SplashScreenWorker: SplashScreenWorkerProtocol {
    
    // MARK: - Private Properties
    private var service: ClientAPISplashScreenProtocol
    
    // MARK: - Init
    init(_ service: ClientAPISplashScreenProtocol = ClientAPI()) {
        self.service = service
    }
    
    func getSplashScreen(completionHandler: @escaping (Result<SplashScreenModels.Fetch.Response, APIError>) -> Void) {
        service.getSplashScreen(completionHandler: { result in
            switch result {
            case .success(let value):
                completionHandler(.success(value))
            case .failure(let error):
                completionHandler(.failure(APIError(status: error.status, message: error.message)))
            }
        })
    }
}
