//
//  SplashScreenRouter.swift
//  phincon-attendance-app
//
//  Created by Ade on 4/25/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SplashScreenRoutingLogic
{
    func routeToDashboard(segue: UIStoryboardSegue?)
    func routeToOnboarding(segue: UIStoryboardSegue?)
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SplashScreenDataPassing
{
  var dataStore: SplashScreenDataStore? { get }
}

class SplashScreenRouter: NSObject, SplashScreenRoutingLogic, SplashScreenDataPassing {
  weak var viewController: SplashScreenVC?
  var dataStore: SplashScreenDataStore?
  
  // MARK: Routing
    
    func routeToDashboard(segue: UIStoryboardSegue?) {
        let tabbarVC = TabBarViewController()
        navigateToDashboard(source: viewController!, destination: tabbarVC)
    }
    
    func routeToOnboarding(segue: UIStoryboardSegue?) {
//        let storyboard = UIStoryboard(name: "Main", bundle: nil)
//        let onboardingVC = storyboard.instantiateViewController(identifier: "NavigationController")
        let onboardingVC = OnBoardingViewController()
        navigateToOnboarding(source: viewController!, destination: onboardingVC)
    }

  // MARK: Navigation
  
    func navigateToOnboarding(source: SplashScreenVC, destination: UIViewController) {
//        let navCon = UINavigationController(rootViewController: destination)
        let navCon = UINavigationController(rootViewController: destination)
        (UIApplication.shared.connectedScenes.first?.delegate as? SceneDelegate)?.changeRootViewController(navCon, animated: true)
    }
    
    func navigateToDashboard(source: SplashScreenVC, destination: UITabBarController) {
        let navCon = UINavigationController(rootViewController: destination)
        (UIApplication.shared.connectedScenes.first?.delegate as? SceneDelegate)?.changeRootViewController(navCon, animated: true)
    }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SplashScreenDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
