//
//  ForgotPasswordPresenter.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 30/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordPresentationLogic
{
  func presentSomething(response: ForgotPassword.Something.Response)
}

class ForgotPasswordPresenter: ForgotPasswordPresentationLogic
{
  weak var viewController: ForgotPasswordDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ForgotPassword.Something.Response)
  {
    let viewModel = ForgotPassword.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
