//
//  DashboardPresenter.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardPresentationLogic {
    func interactor(CheckInLoc response: DashboardModels.IsLogin.location.Response)
    func interactor(CheckOutLoc response: DashboardModels.IsLogin.location.Response)
    func interactor(didExpiredSession status: Int, message: String)
}

class DashboardPresenter: DashboardPresentationLogic {
    
  weak var viewController: DashboardDisplayLogic?
  
  // MARK: Do something
  
    func interactor(CheckInLoc response: DashboardModels.IsLogin.location.Response) {
//        let viewModel = DashboardModels.LoadCheckInOut.ViewModel()
        viewController?.presenter(didLoadCheckInLoc: response)
    }
    
    func interactor(CheckOutLoc response: DashboardModels.IsLogin.location.Response) {
        viewController?.presenter(didLoadCheckOutLoc: response)
    }
    
    func interactor(didExpiredSession status: Int, message: String) {
        viewController?.presenter(expiredLoginSession: status, message: message)
    }
}
