//
//  DashboardInteractor.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardBusinessLogic {
    func loadDashboardListIn(request: DashboardModels.LoadCheckInOut.Request)
    func loadDashboardListOut(request: DashboardModels.LoadCheckInOut.Request)
}

protocol DashboardDataStore {
  //var name: String { get set }
}

class DashboardInteractor: DashboardBusinessLogic, DashboardDataStore {
    var presenter: DashboardPresentationLogic?
    var worker: DashboardWorker?
    
    var checkInList = [Checkin]()
    var checkOutList = [Checkin]()
  //var name: String = ""
  
  // MARK: Do something
    func loadDashboardListIn(request: DashboardModels.LoadCheckInOut.Request) {
        worker = DashboardWorker()
        checkInList = worker!.fetchDashboardListIn()
        
        let response = DashboardModels.LoadCheckInOut.Response(checkInData: checkInList)
        presenter?.presentDashboardListIn(response: response)
    }
    
    func loadDashboardListOut(request: DashboardModels.LoadCheckInOut.Request) {
        worker = DashboardWorker()
        checkOutList = worker!.fetchDashboardListOut()
        
        let response = DashboardModels.LoadCheckInOut.Response(checkInData: checkOutList)
        presenter?.presentDashboardListOut(response: response)
    }
}
