//
//  DashboardRouter.swift
//  phincon-attendance-app
//
//  Created by Ade on 3/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DashboardRoutingLogic
{
  func routeToNotification(segue: UIStoryboardSegue?)
}

protocol DashboardDataPassing
{
  var dataStore: DashboardDataStore? { get }
}

class DashboardRouter: NSObject, DashboardRoutingLogic, DashboardDataPassing {
  weak var viewController: DashboardViewController?
  var dataStore: DashboardDataStore?
  
  // MARK: Routing
  
    func routeToNotification(segue: UIStoryboardSegue?) {
        let storyBoard : UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        
        let notificationVC = storyBoard.instantiateViewController(withIdentifier: "NotificationVC") as! NotificationViewController
//        dashBoardVC.modalPresentationStyle = .fullScreen
        navigateToNotificationVC(source: viewController!, destination: notificationVC)
    }
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
    func navigateToNotificationVC(source: DashboardViewController, destination: NotificationViewController) {
        source.show(destination, sender: nil)
    }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: DashboardDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
