//
//  ForgotPasswordViewController.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 01/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftUI

protocol ForgotPasswordDisplayLogic: AnyObject {
    func displaySomething(viewModel: ForgotPassword.Something.ViewModel)
}

class ForgotPasswordViewController: UIViewController, ForgotPasswordDisplayLogic, ButtonTappedPassDelegate {
    
    var interactor: ForgotPasswordBusinessLogic?
    var router: (NSObjectProtocol & ForgotPasswordRoutingLogic & ForgotPasswordDataPassing)?

  // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
  // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = ForgotPasswordInteractor()
        let presenter = ForgotPasswordPresenter()
        let router = ForgotPasswordRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
  // MARK: Routing
  
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
          let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
          if let router = router, router.responds(to: selector) {
            router.perform(selector, with: segue)
          }
        }
    }
  
  // MARK: View lifecycle
  
  override func viewDidLoad() {
      super.viewDidLoad()
      doSomething()
     
  }
    weak var customForgotPassView : ForgotPasswordView!
    
    override func loadView() {
        super.loadView()
        setupUINib()
    }
    
    func setupUINib() {
        let screenRect = UIScreen.main.bounds
        let screenWidth = screenRect.size.width
        let screenHeight = screenRect.size.height
        
        let forgotPassView = ForgotPasswordView(frame: CGRect(x: 0, y: 0, width: screenWidth, height: screenHeight))
        self.view = forgotPassView
        forgotPassView.delegate = self
        self.customForgotPassView = forgotPassView
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
    
  
  func doSomething()
  {
    let request = ForgotPassword.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: ForgotPassword.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    func didTappedResetPassButton(forgotPasswordView: ForgotPasswordView) {
        customForgotPassView.spinnerSetup(isLogin: true, message: nil, router: self.router as! ForgotPasswordRouter)
    }
    
    func didTappedLoginButton() {
        router?.routeToLogin(segue: nil)
    }
    
}
