//
//  ProfilModels.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 23/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProfilModel {
    
    enum LoadProfil {
        struct Request {}
        struct Response {
            var ProfileData: [Profile]
            var ProfilePicture : [ProfileImage]
        }
        struct ViewModel{
            var titleData : String?
            var imageData : UIImage?
            var descDAta : String?
            var name : String?
            var role : String?
            var image : UIImage
        }
        
    }
}
