//
//  ProfilViewController.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 23/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol ProfilDisplayLogic: AnyObject
{
    func displaySomething(profile: ProfilModel.LoadProfil.Response)
}

class ProfilViewController: UIViewController, ProfilDisplayLogic {
    var interactor: ProfilBusinessLogic?
    var router: (NSObjectProtocol & ProfilRoutingLogic & ProfilDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ProfilInteractor()
        let presenter = ProfilPresenter()
        let router = ProfilRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        fetchProfileData()
        
    }
    
    // MARK: Do something
    
    
    var profileData: [Profile] = []
    var profileImage : [ProfileImage] = []
    
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var editButton : UIButton!
    
    func setupProfil(){
        tableView.register(ProfilTableViewCell.nib(), forCellReuseIdentifier: ProfilTableViewCell.identifier)
        tableView.register(ProfilePictureTableViewCell.nib(), forCellReuseIdentifier: ProfilePictureTableViewCell.identifier)
        tableView.delegate = self
        tableView.dataSource = self
        tableView.estimatedRowHeight = 72
        tableView.layer.cornerRadius = 18
    }
    
    func fetchProfileData()
    {
        let request = ProfilModel.LoadProfil.Request()
        interactor?.doSomething(request: request)
        setupProfil()
    }
    
    func displaySomething(profile: ProfilModel.LoadProfil.Response)
    {
        profileData = profile.ProfileData
        profileImage = profile.ProfilePicture
    }
    
    @IBAction func editButton(_ sender: Any) {
        router?.routeToEditProfilePage(segue: nil)
    }
    
}
extension ProfilViewController : UITableViewDelegate, UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 2
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if section == 0 {
            return profileImage.count
        } else {
            return profileData.count
        }
        
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.section == 0 {
            let cell = tableView.dequeueReusableCell(withIdentifier: ProfilePictureTableViewCell.identifier, for: indexPath) as! ProfilePictureTableViewCell
            let profilObject = profileImage[indexPath.row]
            cell.setupprofileImage(with: profilObject)
            return cell
        } else {
            let cell = tableView.dequeueReusableCell(withIdentifier: ProfilTableViewCell.identifier, for: indexPath) as! ProfilTableViewCell
            let profilObject = profileData[indexPath.row]
            cell.setupProfilView(with: profilObject)
            return cell
        }
        
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        if indexPath.section == 0 {
            return UITableView.automaticDimension
        } else {
            let ratio = UIScreen.main.bounds.height / 736
            return tableView.estimatedRowHeight * ratio
        }
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
    }
    
}
