//
//  ProfilModels.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 23/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProfilModel {
    
    enum LoadProfil {
        struct Request {}
        struct Response: Codable {
            var success: Result?
        }
        struct Result: Codable {
            var status: Int?
            var message: String?
            var result: ProfileResult?
        }
        struct ProfileResult: Codable {
            var id, username, password, fullname: String?
            var idcardnumber: Int?
            var address, image: String?
            var location: [Location]?
            var createdAt, updatedAt, v: Int?

            enum CodingKeys: String, CodingKey {
                case id = "_id"
                case username, password, fullname, idcardnumber, address, image, location, createdAt, updatedAt
                case v = "__v"
            }
        }
        
        // MARK: - Location
        struct Location: Codable {
            var name, address, latitude, longitude: String?
            var image, id: String?

            enum CodingKeys: String, CodingKey {
                case name, address, latitude, longitude, image
                case id = "_id"
            }
        }
    }
}
