//
//  ProfilRouter.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 23/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProfilRoutingLogic {
    func routeToEditProfilePage(segue: UIStoryboardSegue?)
    func routeToLogoutUser(segue: UIStoryboardSegue?)
}

protocol ProfilDataPassing
{
    var dataStore: ProfilDataStore? { get }
}

class ProfilRouter: NSObject, ProfilRoutingLogic, ProfilDataPassing {
    
    weak var viewController: ProfilViewController?
    var dataStore: ProfilDataStore?
    

    // MARK: Routing
    
    func routeToEditProfilePage(segue: UIStoryboardSegue?) {
        let editProfileVC = EditProfileViewController()
        navigateToEditProfile(source: viewController!, destination: editProfileVC)
    }
    
    func routeToLogoutUser(segue: UIStoryboardSegue?) {
//        let storyboard = UIStoryboard(name: "Main", bundle: nil)
//        let onboardingNavController = storyboard.instantiateViewController(identifier: "NavigationController")// root VC of Onboard
        let onboardingVC = OnBoardingViewController()
        let navCon = UINavigationController(rootViewController: onboardingVC)
        navigateToOnboard(source: viewController!, destination: navCon)
    }
    
    // MARK: Navigation
    
    func navigateToEditProfile(source: ProfilViewController, destination: EditProfileViewController) {
        source.show(destination, sender: nil)
    }
    
    func navigateToOnboard(source: ProfilViewController, destination: UINavigationController) {
        (UIApplication.shared.connectedScenes.first?.delegate as? SceneDelegate)?.changeRootViewController(destination, animated: false)
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: ProfilDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
