//
//  ProfilInteractor.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 23/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilBusinessLogic {
    func loadProfile(request: ProfilModels.LoadProfil.Request)
}

protocol ProfilDataStore
{
    //var name: String { get set }
}

class ProfilInteractor: ProfilBusinessLogic, ProfilDataStore {
    
    var presenter: ProfilPresentationLogic?
    var worker: ProfilWorker?
    let userDefault = UserDefaults.standard
    var token: String = ""
    
    // MARK: Do something
    func loadProfile(request: ProfilModels.LoadProfil.Request) {
        worker = ProfilWorker()
        token = userDefault.string(forKey: "user_token")!
        worker?.loadProfile(token: token, completionHandler: { result in
            switch result {
            case .success(let value):
                self.presenter?.interactor(loadProfile: value) //<<< harus lakukan ini biar update data ke VC
                print("success profile")
            case .failure(let error):
                print(error.status, error.message!)
            }
        })
    }
}
