//
//  RegisterRouter.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 30/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegisterRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToLogin(segue: UIStoryboardSegue?)
}

protocol RegisterDataPassing
{
  var dataStore: RegisterDataStore? { get }
}

class RegisterRouter: NSObject, RegisterRoutingLogic, RegisterDataPassing
{
  weak var viewController: RegisterViewController?
  var dataStore: RegisterDataStore?
    
    func routeToLogin(segue: UIStoryboardSegue?) {
        let storyBoard : UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        
        let dashBoardVC = storyBoard.instantiateViewController(withIdentifier: "LoginPage")
        dashBoardVC.modalPresentationStyle = .fullScreen
        navigateToSomewhere(source: viewController!, destination: dashBoardVC as! LoginViewController)
    }
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  func navigateToSomewhere(source: RegisterViewController, destination: LoginViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: RegisterDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
