//
//  LoginInteractor.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 23/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func login(_ request: LoginModels.Post.Request)
}

protocol LoginDataStore {
//    var username: String { get set }
//    var password: String { get set }
}

class LoginInteractor: LoginDataStore {
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    
    // MARK: - Init
}

extension LoginInteractor: LoginBusinessLogic {
    // MARK: Do something
    
    func login(_ request: LoginModels.Post.Request) {
        worker = LoginWorker()
        worker?.postLogin(username: request.username, password: request.password, success: {(user) in
            
            var response: LoginModels.Post.Response?
                        
            //business logic here if any
                        
            if let response = response {
                self.presenter?.interactor(didSuccessLogin: response)
            }
            
        }, fail: { (message) in
            self.presenter?.interactor(didFailLogin: message)
        })
      
//        let response = LoginModels.Post.Response()
//        self.presenter!.presentSomething(response: response)
    }
}
