//
//  LoginWorker.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 23/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginWorkerProtocol: AnyObject {
    func postLogin(username: String, password:String, success: @escaping(_ response: User) -> Void, fail:@escaping(_ message: String) -> Void)
}

class LoginWorker: LoginWorkerProtocol {
    // MARK: - Private Properties
    private var service: ClientAPIProtocol
    
    // MARK: - Init
    init(_ service: ClientAPIProtocol = ClientAPI()) {
        self.service = service
    }
    
    func postLogin(username: String, password: String, success: @escaping (User) -> Void, fail: @escaping (String) -> Void) {
        service.postLogin(username: username, password: password) { (result) in
            
            switch result {
            case .success(_):
                print(result)
            case .failure(_):
                print("fail return worker")
            }
//            let user = User(username: username, password: password)
//            success(user)
            
            
//        } fail: { (message) in
//            print(message)
//        }
        }
    }
}
