//
//  LoginModels.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 23/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LoginModels {
  // MARK: Use cases
  
    enum Post {
        struct Request {
            let username: String
            let password: String
        }
        // MARK: - Response
        struct Response: Codable {
            var success: Success?
        }

        // MARK: - Success
        struct Success: Codable {
            var status: Int?
            var message, token: String?
        }
        
        struct ResponseError: Error {
            let error: ErrorStatus
        }
        // MARK: - Error
        struct ErrorStatus {
            let status: Int
            let message: String
        }
        struct ViewModel {
            let username: String
        }
    }
}
