//
//  ChangePasswordWorker.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 27/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangePasswordWorkerProtocol : AnyObject {
    func changePassword(token: String, password: String, newpassword: String, confirmpassword: String, completionHandler: @escaping (Result<ChangePasswordModel.Put.Response, APIError>) -> Void)
}
class ChangePasswordWorker : ChangePasswordWorkerProtocol {
    private var service: ClientAPIProtocol
    
    init(_ service: ClientAPIProtocol = ClientAPI()) {
        self.service = service
    }
    
    func changePassword(token: String, password: String, newpassword: String, confirmpassword: String, completionHandler: @escaping (Result<ChangePasswordModel.Put.Response, APIError>) -> Void) {
        service.changePassword(token: token, password: password, newpassword: newpassword, confirmpassword: confirmpassword) {
            (result) in
            switch result {
            case .success(let value):
                completionHandler(.success(value))
            case .failure(let error):
                completionHandler(.failure(APIError(status: error.status, message: error.message)))
            }
        }
    }
    
    
  
}
