//
//  ChangePasswordPresenter.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 27/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangePasswordPresentationLogic
{
    func interactor(didChange response: ChangePasswordModel.Put.Response)
    func interactor(didFailedChange error: String)
}

class ChangePasswordPresenter: ChangePasswordPresentationLogic
{
  weak var viewController: ChangePasswordDisplayLogic?
  
  // MARK: Do something
  
    func interactor(didChange response: ChangePasswordModel.Put.Response)
  {
      let viewModel = ChangePasswordModel.Put.ViewModel(message: response.success.message)
    viewController?.presenter(didChange: viewModel)
  }
    func interactor(didFailedChange error: String) {
        viewController?.presenter(didFailedChange: error)
    }
}
