//
//  ChangePasswordViewController.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 27/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangePasswordDisplayLogic: AnyObject
{
    func presenter(didChange viewModel: ChangePasswordModel.Put.ViewModel)
    func presenter(didFailedChange message: String)
}

class ChangePasswordViewController: UIViewController, ChangePasswordDisplayLogic
{
  var interactor: ChangePasswordBusinessLogic?
  var router: (NSObjectProtocol & ChangePasswordRoutingLogic & ChangePasswordDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ChangePasswordInteractor()
    let presenter = ChangePasswordPresenter()
    let router = ChangePasswordRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
   
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var currentPassTextField : UITextField!
    @IBOutlet weak var newPassTextField : UITextField!
    @IBOutlet weak var repeatPassTextField : UITextField!
    @IBOutlet weak var saveButton : UIButton!
    @IBOutlet weak var cardView : UIView!
    
    var updatePassword : [Users] = []
  
    func presenter(didChange viewModel: ChangePasswordModel.Put.ViewModel) {
        print("oke changepass")
    }
    func presenter(didFailedChange message: String) {
        print(message)
    }
}
