//
//  EditProfileInteractor.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 30/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditProfileBusinessLogic
{
    func doSomething(request: EditProfileModel.LoadEditProfile.Request)
}

protocol EditProfileDataStore
{
    //var name: String { get set }
}

class EditProfileInteractor: EditProfileBusinessLogic, EditProfileDataStore
{
    var presenter: EditProfilePresentationLogic?
    var worker: EditProfileWorker?
    var editProfile = [EditProfileData]()
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: EditProfileModel.LoadEditProfile.Request)
    {
        worker = EditProfileWorker()
        editProfile = worker!.fetchEditProfile()
        
        let response = EditProfileModel.LoadEditProfile.Response(Editdata: editProfile)
        presenter?.presentSomething(response: response)
    }
}
