//
//  EditProfileViewController.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 30/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditProfileDisplayLogic: AnyObject
{
    func presenter(didChange viewModel: EditProfileModel.Put.ViewModel)
    func presenter(didFailedChange message: String)
}

class EditProfileViewController: UIViewController, EditProfileDisplayLogic {
    
    var interactor: EditProfileBusinessLogic?
    var router: (NSObjectProtocol & EditProfileRoutingLogic & EditProfileDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = EditProfileInteractor()
        let presenter = EditProfilePresenter()
        let router = EditProfileRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.setNavigationBarHidden(true, animated: false)
    }
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
    }
    
    // MARK: Do something
    
    weak var customEditView: EditProfileView!
    
    //@IBOutlet weak var nameTextField: UITextField!
    override func loadView() {
        super.loadView()
        setupView()
    }
    
    func setupView() {
        let screenRect = UIScreen.main.bounds
        let screenHeight = screenRect.size.height
        let screenWidth = screenRect.size.width
        
        let editProfileView = EditProfileView(frame: CGRect(x: 0, y: 0, width: screenWidth, height: screenHeight))
        self.view = editProfileView
        editProfileView.delegate = self
        self.customEditView = editProfileView
    }
    
    func setupAlert(isSuccess: Bool, error message: String?) {
        if isSuccess {
            let alert = UIAlertController(title: "Profile Updated", message: message, preferredStyle: UIAlertController.Style.alert)
            alert.addAction(UIAlertAction(title: "OK", style: UIAlertAction.Style.default, handler: nil))
            self.present(alert, animated: true, completion: nil)
        } else {
            let alert = UIAlertController(title: "Failed Edit Profile", message: message, preferredStyle: UIAlertController.Style.alert)
            alert.addAction(UIAlertAction(title: "OK", style: UIAlertAction.Style.default, handler: nil))
            self.present(alert, animated: true, completion: nil)
        }
    }
    
    func presenter(didChange viewModel: EditProfileModel.Put.ViewModel) {
        customEditView.setupSpinner(isSuccess: true, message: "")
        DispatchQueue.main.asyncAfter(deadline: .now() + 2.5) {
            self.setupAlert(isSuccess: true, error: "")
        }
    }
    
    func presenter(didFailedChange message: String) {
        customEditView.setupSpinner(isSuccess: false, message: message)
        DispatchQueue.main.asyncAfter(deadline: .now() + 2.5) {
            self.setupAlert(isSuccess: false, error: message)
        }
    }
}

extension EditProfileViewController : ButtonTapedDelegate {
    func didTappedSaveButton() {
        let request = EditProfileModel.Put.Request(fullname: customEditView.nameTextField.text!, address: customEditView.addressTextField.text!)
        interactor?.editProfile(request)
    }
    func didTappedBackButton() {
        self.navigationController?.popViewController(animated: true)
    }
}
