//
//  EditProfileModels.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 30/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EditProfileModel {
    
    enum Put {
        struct Request {
            var fullname: String?
            var username: String?
            var idcardnumber: String?
        }
        struct Response : Codable{
            var success: LoggedIn.Success<Users>
        }
        
    }
}
