//
//  EditProfileInteractor.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 30/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftKeychainWrapper

protocol EditProfileBusinessLogic
{
    func editProfile(_ request: EditProfileModel.Put.Request)
}

protocol EditProfileDataStore
{
    //var name: String { get set }
}

class EditProfileInteractor: EditProfileBusinessLogic, EditProfileDataStore
{
    
    var presenter: EditProfilePresentationLogic?
    var worker: EditProfileWorker?
    let keyChanWrapper = KeychainWrapper.standard
    var token : String = ""
    
    
    // MARK: Do something
    func editProfile(_ request: EditProfileModel.Put.Request) {
        worker = EditProfileWorker()
        token = keyChanWrapper.string(forKey: "user_token")!
        worker?.putEditProfile(token: token, fullname: request.fullname!, idcardnumber: request.idcardnumber!, address: request.address!, completionHandler: { (result) in
            switch result {
            case .success(let value):
                var response: EditProfileModel.Put.Response?
                
                print(value.success)
                response = EditProfileModel.Put.Response(success: value.success)
                
                if let respons = response {
                    self.presenter?.interactor(didChange: respons)
                    print("Success Edit Profile")
                }
            case .failure(let error):
                self.presenter?.interactor(didFailedChange: error.message!)
                print("Failed Edit Profile")
                
            }
        })
    }
    
    
}
