//
//  EditProfileWorker.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 30/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class EditProfileWorker
{
    var editProfile = [EditProfileData]()
   
    
    func fetchEditProfile() -> [EditProfileData] {
        editProfile = [EditProfileData(titleData: "New Address", descData: "Jakarta Selatan", iconData: UIImage(named: "book")),
                       EditProfileData(titleData: "New Password", descData: "**********", iconData: UIImage(named: "password")),
                       EditProfileData(titleData: "Repeat Password", descData: "**********", iconData: UIImage(named: "password"))
        ]
        return editProfile
    }
}
