//
//  EditProfileRouter.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 30/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EditProfileRoutingLogic
{
    func routeToProfile(segue: UIStoryboardSegue?)
}

protocol EditProfileDataPassing
{
    var dataStore: EditProfileDataStore? { get }
}

class EditProfileRouter: NSObject, EditProfileRoutingLogic, EditProfileDataPassing
{
    func routeToProfile(segue: UIStoryboardSegue?) {
        let storyBoard : UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        let profileVC = storyBoard.instantiateViewController(withIdentifier: "TabBarController") as! UITabBarController
        profileVC.modalPresentationStyle = .fullScreen
        navigateToSomewhere(source: viewController!, destination: profileVC)
    }
    
    weak var viewController: EditProfileViewController?
    var dataStore: EditProfileDataStore?
    let userDefault = UserDefaults.standard
    
    // MARK: Routing
    
   
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: EditProfileViewController, destination: UITabBarController)
    {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: EditProfileDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
