//
//  EditProfileModels.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 30/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EditProfileModel {
    
    enum LoadEditProfile {
        struct Request {}
        struct Response {
            var Editdata : [EditProfileData]
        }
        struct ViewModel{
            var title : String?
            var desc : String?
            var icon : UIImage?
        }
    }
}
