//
//  RegisterWorker.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 01/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

protocol RegisterWorkerProtocol: AnyObject {
    func postRegister(username: String, password: String, fullname: String, idcardnumber: String, completionHandler: @escaping (Result<RegisterModels.Post.Response, NSError>) -> Void)
}

class RegisterWorker: RegisterWorkerProtocol {
    // MARK: - Private Properties
    private var service: ClientAPIProtocol
    
    // MARK: - Init
    init(_ service: ClientAPIProtocol = ClientAPI()) {
        self.service = service
    }
    func postRegister(username: String, password: String, fullname: String, idcardnumber: String, completionHandler: @escaping (Result<RegisterModels.Post.Response, NSError>) -> Void) {
        service.postRegister(username: username, fullname: fullname, password: password, idnumber: idcardnumber, completionHandler: { result in
            completionHandler(result)
        })
    }
    
    
}
