//
//  RegisterInteractor.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 01/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterBusinessLogic {
    func register(_ request: RegisterModels.Post.Request)
}

protocol RegisterDataStore {
  //var name: String { get set }
}

class RegisterInteractor: RegisterBusinessLogic, RegisterDataStore {
    var presenter: RegisterPresentationLogic?
    var worker: RegisterWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func register(_ request: RegisterModels.Post.Request) {
        worker = RegisterWorker()
        worker?.postRegister(username: request.username!, password: request.password!, fullname: request.fullname!, idcardnumber: request.idcardnumber!, completionHandler: { (result) in
            
            switch result {
            case .success(let value):
                var response: RegisterModels.Post.Response?

                //business logic here if any
                if value != nil {
                    print(value.success)
                    response = RegisterModels.Post.Response(success: value.success)
                }
                if let respons = response {
                    self.presenter?.interactor(didSuccessRegister: respons)
                }
            case .failure(let error):
                self.presenter?.interactor(didFailRegister: "error")
            }
        })
    }
}
