//
//  RegisterPresenter.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 01/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPresentationLogic
{
  func presentSomething(response: Register.Something.Response)
}

class RegisterPresenter: RegisterPresentationLogic
{
  weak var viewController: RegisterDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Register.Something.Response)
  {
    let viewModel = Register.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
