//
//  RegisterPresenter.swift
//  phincon-attendance-app
//
//  Created by Sri Endah Ramurti on 01/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPresentationLogic {
    func interactor(didSuccessRegister response: RegisterModels.Post.Response)
    func interactor(didFailRegister error: String)
}

class RegisterPresenter: RegisterPresentationLogic {
    
  weak var viewController: RegisterDisplayLogic?
  
  // MARK: Do something
    
    func interactor(didSuccessRegister response: RegisterModels.Post.Response) {
        let viewModel = RegisterModels.Post.ViewModel(message: response.success.message)
        viewController?.presenter(displayRegisterSuccess: viewModel)
    }
    
    func interactor(didFailRegister error: String) {
        viewController?.presenter(didFailRegister: error)
    }
  
//  func presentSomething(response: RegisterModels.Post.Response) {
//    let viewModel = RegisterModels.Post.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
